server:
  port: 8084

spring:
  application:
    name: transactions-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/bankx
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Console H2
  h2:
    console:
      enabled: false #No es compatible con WebFLUX
      #path: /h2-console

# Logging
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.reactive: DEBUG

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics

#Resilience4j config
resilience4j:
  circuitbreaker:
    instances:
      riskClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      riskClient:
        maxAttempts: 3
        waitDuration: 200ms
  timelimiter:
    instances:
      riskClient:
        timeoutDuration: 1s